config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  get "up" => "rails/health#show", as: :rails_health_check

  resources :rockets do
    collection do
      get :myrockets
    end
    resources :bookings, only: [:new, :create]
  end

  # Bookings routes
  resources :bookings, only: [:index, :show, :edit, :update, :destroy] do
    collection do
      get :mine
    end
  end

  patch "bookings/:id/accept", to: "bookings#accept", as: 'accept'
  patch "bookings/:id/reject", to: "bookings#reject", as: 'reject'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :rocket

  validates :status, inclusion: { in: %w[pending accepted canceled rejected] }
  validates :number_of_days, :full_price, presence: true
end

app/models/rocket.rb
class Rocket < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos

  validates :name, :content, :number_passengers, :price_per_day, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :rockets
  has_many :bookings
  # has_many :rented_rockets, through: :bookings, source: :rocket
  has_many :bookings_on_my_rockets, through: :rockets, source: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_rocket, only: %i[new create]

  def index
    @bookings = Booking.all
  end

  def new
    @booking = @rocket.bookings.new
  end


  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to mine_bookings_path
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def mine
    @rockets = current_user.rockets
    @bookings = current_user.bookings
    @requests = Booking.includes(:user, :rocket).where(rocket: current_user.rockets)
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.update(status: "accepted")
    redirect_to mine_bookings_path
  end

  def reject
    @booking = Booking.find(params[:id])
    @booking.status = "rejected"
    @booking.save
    redirect_to mine_bookings_path
  end

  def create
    @booking = @rocket.bookings.new(booking_params)
    @booking.user = current_user
    @booking.number_of_days = compute_days(params[:booking][:date_range])
    @booking.full_price = @booking.number_of_days * @booking.rocket.price_per_day
    @booking.start_date = Date.parse(params[:booking][:date_range].first(10))
    @booking.end_date = Date.parse(params[:booking][:date_range].last(10))
    @booking.date_range = @booking.start_date..@booking.end_date

    if @booking.save
      redirect_to rocket_path(@rocket), notice: "Booking created successfully!"
    else
      redirect_to rocket_path(@rocket), notice: "Booking not created!"
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:number_of_days, :full_price, :status)
  end

  def set_rocket
    @rocket = Rocket.find(params[:rocket_id])
  end

  def compute_days(range)
    start_date = Date.parse(range.first(10))
    last_date = Date.parse(range.last(10))
    number_of_days = (last_date - start_date).to_i
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/rockets_controller.rb
class RocketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_rocket, only: %i[ show edit update destroy ]

  def myrockets
    @rockets = current_user.rockets
  end

  def index
    @rockets = Rocket.all
    if params[:query].present?
      sql_subquery = <<~SQL
        rockets.name @@ :query
        OR rockets.content @@ :query
      SQL
      @rockets = @rockets.where(sql_subquery, query: params[:query])
    end
  end

  def show
    @booking = Booking.new(rocket: @rocket)
  end

  def new
    @rocket = Rocket.new
  end

  def create
    @rocket = Rocket.new(params_rocket)
    @rocket.user = current_user
    if @rocket.save
      redirect_to rocket_path(@rocket)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @rocket = Rocket.find(params[:id])
  end

  def update
    @rocket.update(params_rocket)
    redirect_to mine_bookings_path
  end

  def destroy
    @rocket = Rocket.find(params[:id])
    @rocket.destroy
    redirect_to mine_bookings_path
  end

  private

  def params_rocket
    params.require(:rocket).permit(:name, :content, :price_per_day, :number_passengers, photos: [])
  end

  def set_rocket
    @rocket = Rocket.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div>
  <div class="m-3">
    <%= simple_form_for([@rocket, @booking], html: { id: "rocketForm", data: { controller: "rocket", action: "submit->rocket#animate" } }) do |f| %>
      <%= f.input :date_range,
                  as: :string,
                  label: "When would you like to travel ?",
                  input_html: {
                    data: {
                      action: "change->datepicker#checkDateRange",
                      datepicker_target: "input"
                    }
                  } %>
        <%= f.submit "Confirm your booking", class: "btn btn-primary btn-lg shadow-lg" %>
    <% end %>
  </div>
</div>

app/views/bookings/edit.html.erb
<div>
    <%= render "form", class:"mb-3" %>
</div>

app/views/bookings/mine.html.erb
<div class="container ">
  <ul class="nav nav-tabs justify-content-center" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="btn nav-link active booking-tab" id="home-tab" data-bs-toggle="tab" data-bs-target="#home-tab-pane" type="button" role="tab" aria-controls="home-tab-pane" aria-selected="true">My bookings</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="btn nav-link booking-tab" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="false">My requests</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="btn nav-link booking-tab" id="rockets-tab" data-bs-toggle="tab" data-bs-target="#rockets-tab-pane" type="button" role="tab" aria-controls="rockets-tab-pane" aria-selected="false">My rockets</button>
    </li>
  </ul>
</div>

<%# MY BOOKINGS TAB %>
<div class="tab-content position-sticky" id="myTabContent">
  <div class="tab-pane fade show active" id="home-tab-pane" role="tabpanel" aria-labelledby="home-tab" tabindex="0">
    <div class="container justify-content-center">
      <% @bookings.each do |booking| %>
          <div class="d-flex justify-content-between card-product m-2 rounded-4 border-2 border-white bg-white" style="--bs-bg-opacity: .25">
            <%= cl_image_tag booking.rocket.photos.first.key%>
            <div class="card-product-infos">
              <h2 class="card-title mb-2"><%= booking.rocket.name %></h2>
              <p class="card-text m-0"><%= booking.rocket.content %></p>
            </div>
            <div class="card-product-infos">
              <h2 class="card-title mb-2"><strong>Booking details</strong></h2>
              <p class="card-text m-0"> Booked for <strong><%= booking.number_of_days %> day</strong></p>
              <p class="card-text m-0"> From <strong><%= booking.start_date %></strong> to <strong><%= booking.end_date %></strong> </p>
              <p class="card-text m-0"> Total price : <strong><%= booking.full_price %>M $</strong></p>
              <p class="card-text m-0"> Status : <strong><%= booking.status %></strong></p>
            </div>
            <div class="card-product-infos position-relative mt-3">
              <%= link_to "cancel", booking_path(booking), class:"btn btn-cards btn-outline-danger position-absolute top-50 start-0", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
            </div>
          </div>
      <% end %>
    </div>
  </div>

<%# MY REQUESTS %>
  <div class="tab-pane fade position-sticky" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="0">
    <div class="container justify-content-center">
      <% @rockets.each do |rocket| %>
        <%= rocket.bookings.each do |booking| %>
          <div class="d-flex justify-content-between card-product m-2 rounded-4 border-2 border-white bg-white" style="--bs-bg-opacity: .25" data-controller="status">
            <%= cl_image_tag booking.rocket.photos.first.key %>
            <div class="card-product-infos">
              <h2 class="card-title mb-2"><%= booking.rocket.name %></h2>
              <p class="card-text m-0"><%= booking.rocket.content %></p>
            </div>
            <div class="card-product-infos">
              <h2 class="card-title mb-2"><strong>booking details</strong></h2>
              <p class="card-text m-0"> Booked for <strong><%= booking.number_of_days %> day</strong></p>
              <p class="card-text m-0"> From <strong><%= booking.start_date %></strong> to <strong><%= booking.end_date %></strong> </p>
              <p class="card-text m-0"> Total price : <strong><%= booking.full_price %>M $</strong></p>
              <p class="card-text m-0" data-status-target="currentstatus"> Status : <strong><%= booking.status %></strong></p>
            </div>
            <div class="card-product-infos position-relative mt-3" data-status-target="divbutton">
              <%= link_to "Accept", accept_path(booking), data: { turbo_method: :patch }, class: "btn btn-cards btn-outline-success position-absolute top-40 start-0" %>
              <%= link_to "Reject", reject_path(booking), data: { turbo_method: :patch }, class: "btn btn-cards btn-outline-danger position-absolute top-50 start-0" %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

<%# MY ROCKETS %>
  <div class="tab-pane fade position-sticky" id="rockets-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="0">
    <div class="container justify-content-center">
          <% @rockets.each do |rocket| %>
          <div class="d-flex justify-content-between card-product m-2 rounded-4 border-2 border-white bg-white" style="--bs-bg-opacity: .25">
            <%if rocket.photos.attached?%>
              <%= cl_image_tag rocket.photos.first.key%>
              <div class="card-product-infos">
                <h2 class="card-title mb-2"><%= rocket.name %></h2>
                <p class="card-text m-0"><%= rocket.content %></p>
              </div>
              <div class="card-product-infos">
                <h2 class="card-title mb-2"><strong>Rocket details</strong></h2>
                <p class="card-text m-0"> Number of passengers : <strong><%= rocket.number_passengers %> </strong></p>
                <p class="card-text m-0"> Price :  <strong><%= rocket.price_per_day %></strong>M $/day </strong> </p>
              </div>
            <%else%>
              <div class="card-product-infos">
                <h2 class="card-title mb-2"><%= rocket.name %></h2>
                <p class="card-text m-0"><%= rocket.content %></p>
              </div>
              <div class="card-product-infos">
                <h2 class="card-title mb-2"><strong>Rocket details</strong></h2>
                <p class="card-text m-0"> Number of passengers : <strong><%= rocket.number_passengers %> </strong></p>
                <p class="card-text m-0"> Price :  <strong><%= rocket.price_per_day %></strong>M $/day </strong> </p>
              </div>
              <%end%>
            <div class="card-product-infos position-relative mt-3">
              <%= link_to "Edit", edit_rocket_path(rocket), class: "btn btn-cards btn-outline-success position-absolute top-40 start-0"%>
              <%= link_to "Delete", rocket_path(rocket), class:"btn btn-cards btn-outline-danger position-absolute top-50 start-0", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
            </div>
          </div>
      <% end %>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirBorbit</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
    <% unless current_page?(root_path) %>
      <body style="background-image: https://s2.best-wallpaper.net/wallpaper/3840x2160/1803/NGC-7380-Wizard-Nebula-stars-universe_3840x2160.jpg">
      <%= render "shared/navbar" %>
      <div class="notices">
        <%= content_tag(:p, notice, class: "notice btn btn-warning btn-lg fs-2 rounded-pill border border-white border-2 fw-bold text-white") if notice.present? %>
        <%= content_tag(:p, alert, class: "alert") if alert.present? %>
      </div>
    <% end %>
    <%= yield %>  
    <% unless current_page?(root_path) %>
      <footer>
        <%= render 'shared/footer' %>
      </footer>
    <% end %>
  </body>
</html>


<%# <%= link_to "My dashborad", myrockets_user_rockets_path(user_id: current_user.id) %>

app/views/pages/home.html.erb
<div class="background-image d-flex justify-content-center align-items-center flex-column text-center">
  <%= image_tag "logo_rocket_colored.png", class: "rounded-circle mb-5", id: "home-logo" %>

  <%= link_to "Hey Pilot, get ready to fly!", rockets_path, class: "btn btn-warning btn-lg fs-2 rounded-pill border border-white border-2 fw-bold text-white" %>
</div>

app/views/rockets/_form.html.erb
<div class="container-sm mt-5 login rounded-3 shadow-sm">
  <div class="m-3 p-3">
  <%= simple_form_for(@rocket) do |f| %>
    <%= f.input :name, wrapper_html: { class: 'text-primary' } %>
    <%= f.input :content %>
    <%= f.input :number_passengers %>
    <%= f.input :price_per_day %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit class: "btn btn-primary btn-lg" %>
  <% end %>
  </div>
</div>

app/views/rockets/edit.html.erb
<div class="d-flex">
  <div class="col-2 d-flex align-items-center justify-content-center">
    <a href="<%= rockets_path %>" class="text-decoration-none">
      <i id="return-button" class="fa-solid fa-circle-arrow-left" style="color: #fca311; font-size: 40px;"></i>
    </a>
  </div>
  <%= render "form", class:"mb-3" %>
  <div class="col-2"></div>
</div>

app/views/rockets/index.html.erb
<div id="index" class="container text-center text-white shadow-2 mt-3">

  <%= link_to "Add your rocket", new_rocket_path, class: "shadow-lg btn btn-warning btn-lg", id:"btnaddrocket" %>

<div class="row justify-content-center">

  <h3 class="shadow-2 mt-2 mb-2">Choose your <i class="fa-solid fa-shuttle-space fa-bounce"></i> and get ready for take-off!</h3>

  <div class="col-sm-8 my-3">

      <%= form_with url: rockets_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Find your rocket here..."
          %>
        <%= submit_tag "Search", name: "", class: "btn btn-outline-warning" %>
      <% end %>
    </div>
  </div>

  <%# CARDS OF THE ROCKETS %>
  <div class="row text-center">

    <% @rockets.each do |rocket| %>
      <%= link_to rocket_path(rocket), class: "btn card rounded-4 col-4 p-0 m-5 w-25 border-1 border-white shadow" do%>
        <%if rocket.photos.attached?%>
          <%= cl_image_tag rocket.photos.first.key, alt: "Picture of #{rocket.name}", class: "card-img-top h-100 rounded-top-4" %>
          <div class="card-body">
            <h5 class="card-title mb-2"><strong></strong><%= rocket.name %></h5>
            <p class="card-text m-0"><i class="fa-solid fa-credit-card"></i> <%= rocket.price_per_day %>M$/day</p>
            <p class="card-text m-0"><%= rocket.number_passengers %> <i class="fa-solid fa-user-astronaut"></i></p>
          </div>
        <%else%>
        <div class="card-body">
          <h5 class="card-title mb-2"><strong></strong><%= rocket.name %></h5>
          <p class="card-text m-0"><i class="fa-solid fa-credit-card"></i> <%= rocket.price_per_day %>M $/day</p>
          <p class="card-text m-0"><%= rocket.number_passengers %> <i class="fa-solid fa-user-astronaut"></i></p>
        </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/rockets/new.html.erb
<div class="d-flex">
  <div class="col-2 d-flex align-items-center justify-content-center">
    <a href="<%= rockets_path %>" class="text-decoration-none">
      <i id="return-button" class="fa-solid fa-circle-arrow-left" style="color: #fca311; font-size: 40px;"></i>
    </a>
  </div>
  <%= render "form", class:"mb-3" %>
  <div class="col-2"></div>
</div>

app/views/rockets/show.html.erb
<div class="d-flex">
  <div class="col-2 d-flex align-items-center justify-content-center">
    <a href="<%= rockets_path %>" class="text-decoration-none">
      <i id="return-button" class="fa-solid fa-circle-arrow-left" style="color: #fca311; font-size: 40px;"></i>
    </a>
  </div>

  <div id="show-container" class="container mt-3 align-center">
    <div class="row">
      <div class="col-6 bg-light-grey text-white">
        <div id="carouselExampleIndicators" class="carousel slide">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
          </div>

          <div class="carousel-inner">
            <% @rocket.photos.each_with_index do |photo, index| %>
              <div class="carousel-item <%= 'active' if index == 0 %> carousel-img">
                <%= cl_image_tag photo.key, crop: "lfill", class: "d-block w-100", alt: "Rocket Image" %>
              </div>
            <% end %>
          </div>

          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>

          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </div>

      <div class="col-5 text-white m-4">
        <div class="text-white border-0 shadow-sm rounded p-3">
          <h2 class="rocket-name"><%= @rocket.name %></h2>
          <p class="rocket-details"><strong>Price:</strong> <%= @rocket.price_per_day %>M $ / day</p>
          <p class="rocket-details"><strong>Passenger Capacity:</strong> <%= @rocket.number_passengers %></p>
          <p class="rocket-description"><%= @rocket.content %></p>
        </div>
      </div>
    </div>
  </div>

  <div class="col-2"></div>
</div>

<div class="container mt-3 align-center mt-4">
  <div class="row">
    <div class="col text-center">
      <div data-controller="toggle">
        <button data-action="click->toggle#fire" class="shadow-lg btn btn-warning btn-lg">
          Book the <strong><%= @rocket.name %></strong> now !
        </button>

        <div class="d-none" data-toggle-target="togglableElement" data-controller="datepicker" data-price-value="<%= @rocket.price_per_day %>">
          <div class="d-flex justify-content-center align-items-center">
            <div class="col-4  d-flex bform justify-content-between align-items-center">
              <div class ="ms-3">
                <%= render "bookings/form", rocket: @rocket %>
              </div>
              <div class="me-3">
                <p style="margin-top: 2px;">Total price: </p>
                <p data-datepicker-target="output" id="price-holder">...</p>
                <br><br>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>
<div id="rocket" class="rocket">
  <%= image_tag "rocket.gif" %>
</div>

app/views/shared/_footer.html.erb
<footer>
  <div class="footerz">
    <div class="footer-links">
    <p>&copy; <%= Time.now.year %> AirBorbiT. Tous droits réservés.</p>
    <ul>
        <li><a href="#">Mentions légales</a></li>
        <li><a href="#">Politique de confidentialité</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="bg-transparent navbar navbar-expand-sm navbar-light navbar-lewagon position-sticky top-0" style="z-index: 1050;">
  <div class="container-fluid">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo_rocket_colored.png", class: "rounded-circle" %>
  <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", rockets_path, class: "nav-link", id:"homeLinkHover" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dashboard", mine_bookings_path, class: "nav-link", id:"homeLinkHover" %></li>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "https://futureoflife.org/wp-content/uploads/2020/08/elon_musk_royal_society.jpg", class: "avatar", alt: "dropdown menu" %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>